### PR TITLE
add transitional map panel

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
#404 

### Changes
- This PR adds support for a transitional map panel. This is a config-only implementation for now as we only need it for one project.

### Testing
Steps:
1. Test the demo on different browsers and with different screen resolutions to ensure everything works as expected! Each section should take you to a different point on the map.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)

### CODE REVIEW

**Review by james-rae — CHANGES_REQUESTED** [review]
Just making a note that if you want to support MIL targets, you'll need to expand `PointOfInterestTarget` to have an optional `layerIndex? number` type property. This code would attempt to find graphics in the parent container and :boom:. 
Not sure what the scope & requirements are right now.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv1kEq7BWfsNN72yZlb:b-dfdrop)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/panels/interactive-map.vue` line 99 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv1hA8FCJnKxH0UddQw:-Nv1hA8FCJnKxH0UddQx:b-zh3gkp) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/793a9141c7ec4c92ca5100517f8b720baa8f4267/src/components/panels/interactive-map.vue#L99)):*
> ```Vue
> 
>         // Once the layer has loaded, zoom into the point.
>         layer.loadDefProm.realPromise.then(async () => {
> ```

`layer.loadDefProm.realPromise` can become `layer.loadPromise()`.  The two current ones are private/internal vars; no typescript here to enforce it but implementation could change. 
___
*[`src/components/panels/helpers/point-of-interest-item.vue` line 65 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv1iXCA8DYkXzEzYVze:-Nv1iXCA8DYkXzEzYVzf:b-pw8pu9) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/793a9141c7ec4c92ca5100517f8b720baa8f4267/src/components/panels/helpers/point-of-interest-item.vue#L65)):*
> ```Vue
>             // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>             // @ts-ignore
>             const oid = p.attributes['oid'] ? p.attributes['oid'].value : undefined;
> ```

bit confused here. `p` looks like it is `PointOfInterestTarget`, but that doesn't have `attributes` property. Ramp Graphics do. My main concern here is we are hardcoding an objectid field name to get a value from a Graphic's attributes.   If `attributes` is some fancy way of just doing `p.oid` then all good.

**Review by RyanCoulsonCA — COMMENTED** [review]
Good catch. I've added support for map image layers now.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv28p_r3f226ZqwtNz4:bly8s4h)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @james-rae)

___
*[`src/components/panels/interactive-map.vue` line 99 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv1hA8FCJnKxH0UddQw:-Nv28vC8-TGUBGcIkYiN:b-896fja) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/793a9141c7ec4c92ca5100517f8b720baa8f4267/src/components/panels/interactive-map.vue#L99)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`layer.loadDefProm.realPromise` can become `layer.loadPromise()`.  The two current ones are private/internal vars; no typescript here to enforce it but implementation could change.
</blockquote></details>

Done!
___
*[`src/components/panels/helpers/point-of-interest-item.vue` line 65 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv1iXCA8DYkXzEzYVze:-Nv28w_aC1jAAXBBupxF:beot5k5) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/793a9141c7ec4c92ca5100517f8b720baa8f4267/src/components/panels/helpers/point-of-interest-item.vue#L65)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

bit confused here. `p` looks like it is `PointOfInterestTarget`, but that doesn't have `attributes` property. Ramp Graphics do. My main concern here is we are hardcoding an objectid field name to get a value from a Graphic's attributes.   If `attributes` is some fancy way of just doing `p.oid` then all good.
</blockquote></details>

`p` in this case is actually just an HTML element. This code is grabbing the attributes from the element that the intersection observer is monitoring (the div with the `ref="poi"`) so that we can figure out which point to zoom in to. I was planning on cleaning this function up but forgot, should be better now!

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/panels/interactive-map.vue` line 82 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv2pnprC_eosHn7m0If:-Nv2pnprC_eosHn7m0Ig:b-gi7h69) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/0264aa54cf3f6c31676691f98af8e51250ff38a2/src/components/panels/interactive-map.vue#L82)):*
> ```Vue
>                     const layer = mapInstance.geo.layer.getLayer(target.layerId);
>                     layer.loadPromise().then(() => {
>                         if (target.layerIndex) {
> ```

`0` is valid index and will make this `if` go false.
Same with `&& !layerIndex` and ` layerIndex ? ` farther down this file.

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @james-rae)

___
*[`src/components/panels/interactive-map.vue` line 82 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv2pnprC_eosHn7m0If:-Nv2zG7n8jBYHm-xBAP5:b-vnj4fb) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/0264aa54cf3f6c31676691f98af8e51250ff38a2/src/components/panels/interactive-map.vue#L82)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`0` is valid index and will make this `if` go false.
Same with `&& !layerIndex` and ` layerIndex ? ` farther down this file.
</blockquote></details>

Oops, definitely not the first or last time I'll do this lol. Fixed.
___
*[`src/components/panels/helpers/point-of-interest-item.vue` line 7 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-Nv3-IWU5BkQS6Yq9D9y:-Nv3-IWVDDiy_Hvbk_im:b-t4hakx) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/0264aa54cf3f6c31676691f98af8e51250ff38a2/src/components/panels/helpers/point-of-interest-item.vue#L7)):*
> ```Vue
>         :oid="point.target?.oid"
>         :layerId="point.target?.layerId"
>         :layerIndex="point.target?.layerIndex"
> ```

Realized that this attribute passing garbage was only necessary before I moved the points to their own component. Cleaned up this file a bunch.

**Review by james-rae — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: all files reviewed, 1 unresolved discussion

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

**Review by RyanCoulsonCA — COMMENTED** [review]
I noticed on mobile that the third point of interest (the long one) wasn't zooming because the height of the component in comparison with the window height was too much to hit the 45% threshold. I've enhanced the observer logic to calculate the threshold based on the height of the component and the client height.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv7ZU4F5zpFkHbKpwLN:bcxu2el)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @james-rae, @KashishMistry, and @yileifeng)

**Review by szczz — APPROVED** [review]
Noticed that if you load the page in full screen or half screen the map centers around the point nicely, but if you start full screen and then make the page half screen the map isn't centered around the POI. 

Not sure if this is something we can reasonably detect and handle so won't block.

DM on slack for a GIF if needed. File size is too large to add it here.

> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv7eOwS9o1F8O76_5XM:b-a46fc0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Looks like it's an issue with the component not resizing when you change the window size. I'm looking into it!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv7xy47EPW6wPFp0Hi1:blxvmb4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Had to do some funky CSS width calculations, but this should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420#-:-Nv8E3MHA2IM7Sd-6MeT:bnm7i5p)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @james-rae, @KashishMistry, @szczz, and @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
