### PR TITLE
Migrate Storylines to Vue3

### PR DESCRIPTION
**Pull request by dnlnashed**
Done together with @yileifeng

### Changes ###
- Updated Vue to version 3 (including global API + syntax changes, dynamic components registration, TS)
- Updated certain dependencies to be functional with vue 3 
  - Some notable dependencies are `vue-router`, `vue-i18n`, `vue-fullscreen`, `vue-scrollama`, `vue-tippy`
  - `hooper` was replaced with `vue3-carousel`
  - `vue-loading-spinner` was replaced with `vue3-spinners`
- Refactored options to composition API
  - Removed `vue-property-decorator` and `vue-class-component` as they were only for options API
- Various bugs and styling fixes
  - Functionality and styling should be the same as before

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/386)

### CODE REVIEW

**Comment by dnlnashed** [comment]
Demo link: https://ramp4-pcar4.github.io/story-ramp/upgrade/#/en/00000000-0000-0000-0000-000000000000

**Comment by spencerwahl** [comment]
Only breaking thing I see is I am getting a horizontal scrollbar

**Review by dnlnashed — COMMENTED** [review]
Removed the horizontal scrollbar. Was caused due to 'next' arrow of the slide show panel being placed to far to the right. 

Seems like this was an issue before the refactor, can see the scrollbar still when testing earlier versions of storylines (or through past PR demo links on the main repo).

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/386#-:-NgV4zGg839JfSHZWc-O:b-cmrg60)* status: 0 of 35 files reviewed, all discussions resolved

**Comment by spencerwahl** [comment]
I am still seeing the scrollbar but if it was there before this PR then I think its ok to solve that separately and merge this one.

**Review by dnlnashed — COMMENTED** [review]
Sounds good :thumbsup:. Not sure but I don't think the demo build is updating the change, still seeing the old values in dev tools.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/386#-:-NgZ2_rPB_StEWzn3dtw:b-itdcy7)* status: 0 of 35 files reviewed, all discussions resolved

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 28 files at r2, 1 of 8 files at r3, 3 of 20 files at r4, 1 of 3 files at r6, 26 of 28 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Pull request merged**
