### PR TITLE
Add caption for chart panels

### PR DESCRIPTION
**Pull request by IshavSohal**
### Related Item(s)
https://github.com/ramp4-pcar4/storylines-editor/issues/393 

### Changes
- Added captions for chart panels

### Testing
Steps:
1. Open the demo page
2. Navigate to the dynamic panel with title `This Slide Is Dynamic!`
3. Open the charts panel
4. Observe the caption under each chart of the slideshow
5. Navigate to the `Highcharts Demo` slide
6. Observe the caption under each chart of the slideshow

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507)

### CODE REVIEW

**Review by IshavSohal — COMMENTED** [review]
Donethanks

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507#-:-OCK_p5J2ZggztDAndy8:bah2568)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
With the current implementation, the caption won't be visible if there's a single chart on a slide with a background image:



The solution we use for the [image panel](https://github.com/ramp4-pcar4/story-ramp/blob/main/src/components/panels/image-panel.vue#L14) should work here as well. You should also add the `text-sm` class to the caption so it's consistent with the other captions.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507#-:-OCKmCex5Rb298sS5-ih:bxahv19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Pull request merged**
