### PR TITLE
add scrollguard and title support to map panel

### LINKED ISSUE #148: Allow titles above map instances + navigation issue
Consider http://localhost:8080/#/en/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/#11-ethlyene-glycol-disposal-and-recycling-trends:

image

The clients would like the title on the left to appear above the map, centered. Perhaps adapting the schema to permit a title above the map would satisfy this?

If we eliminate the title from the left-hand pane, however, then we need to make the map pane take up the full slide. This creates a navigation issue because the full-page map wants to pan instead of scroll. Can we implement scroll-lock (ctrl+scroll to pan) in these cases? 

This issue is to both permit a title above a map instance, and to enable scroll-lock on a specified map (which is maybe a config flag I am ignorant of?).

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #148 

Adds a `title` property to the map panel config that will display a title centred above a RAMP map. This PR also adds another property to the map panel called `scrollguard` that will require CTRL be pressed in order to scroll the map. This functions exactly as the scrollguard does in RAMP4.

---
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[src/components/panels/map-panel.vue, line 3 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156#-MvPi39sBLARgh_GqPWN:-MvPi39sBLARgh_GqPWO:bwq4iyt) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/02f888c8ce8bf01b1a4f2c3222dd5b1a45130ef6/src/components/panels/map-panel.vue#L3)):*
> ```Vue
> <template>
>     <div>
>         <div class="px-10 mb-0 chapter-title top-20 map-title text-center">
> ```

might need to adjust some styling here for the mobile resolutions when merged

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[src/components/panels/map-panel.vue, line 3 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156#-MvPi39sBLARgh_GqPWN:-MvPzEee6tHLfSMwcrBv:b-slk9lk) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/02f888c8ce8bf01b1a4f2c3222dd5b1a45130ef6/src/components/panels/map-panel.vue#L3)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

might need to adjust some styling here for the mobile resolutions when merged 
</blockquote></details>

:thumbsup: I've rebased and adjusted styling as needed

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
