### PR TITLE
Add video panel support

### LINKED ISSUE #359: Support for video
Clients have proposed and requested the ability to integrate video in their right-hand panel, which to my mind means support for a new panel type in the schema.

There's an existing WET player we could leverage, we will need to be mindful of accessibility (transcripts, accessible controls, etc):
https://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-en.html

Some considerations:
- Video dimensions
- Full screen video
- Locally hosted video vs. linked from elsewhere vs. YouTube
- Limitations and constraints

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #359 

Worked on with @JahidAhmed 

Added video functionality for basic panels as found in the demo product. Most of the options are already configurable. There are a list of remaining tasks that I wrote as a comment in `video-panel` but can also list here: 

- [x] videos are not working as part of dynamic panels, as seen in the second panel on demo page
- [x] add support for video dimensions + fix the current panel taking up unnecessary space (needs to be fixed even if no dimensions are specified)
- [x] add full screen functionality (not sure how high a priority this is but we have a `vue-fullscreen` component for images already) 
- [x] tied together with the video dimensions, ensure nothing breaks on mobile after fixing point 2
- [x] test to make sure transcript and local video files are working

The first two points here are definitely the highest priority.

**Testing**: 
- video controls accessibility
- working captions
- transcripts embedded below video if included in config 
- general working functionality

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)

### CODE REVIEW

**Review by JahidAhmed — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: 0 of 4 files reviewed, all discussions resolved

**Review by JahidAhmed — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @yileifeng)

___
*[`StoryRampSchema.json` line 295 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_Bq83iD3313WZl0SZN:-N_Bq83iD3313WZl0SZO:b-dkvjdn) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/e30ee14e3021a94545a1ee636fbe21295f530bed/StoryRampSchema.json#L295)):*
> ```JSON
>                 "caption": {
>                     "type": "string",
>                     "description": "Overlaying subtitles on the video, input should be a .vttt file."
> ```

One extra `t`. Should be `.vtt` file
___
*[`src/components/panels/video-panel.vue` line 34 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_BqtRJ9Kuh7X-Cl7zA:-N_BqtRJ9Kuh7X-Cl7zB:bwokhws) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/e30ee14e3021a94545a1ee636fbe21295f530bed/src/components/panels/video-panel.vue#L34)):*
> ```Vue
>                 />
>             </video>
>             
> ```

Is this still a thing? Or was this only when we were using the WET plugin

**Review by yileifeng — COMMENTED** [review]
> Reviewed 5 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: all files reviewed, 3 unresolved discussions (waiting on @JahidAhmed and @spencerwahl)

___
*[`StoryRampSchema.json` line 295 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_Bq83iD3313WZl0SZN:-N_EVTTa8LK9nrFPkfGF:bah2568) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/e30ee14e3021a94545a1ee636fbe21295f530bed/StoryRampSchema.json#L295)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

One extra `t`. Should be `.vtt` file
</blockquote></details>

Donethanks
___
*[`src/components/panels/video-panel.vue` line 34 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_BqtRJ9Kuh7X-Cl7zA:-N_EVUWu7GSrCrX2joK4:b-qao9is) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/e30ee14e3021a94545a1ee636fbe21295f530bed/src/components/panels/video-panel.vue#L34)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Is this still a thing? Or was this only when we were using the WET plugin
</blockquote></details>

Only for WET, removed
___
*[`src/components/panels/video-panel.vue` line 48 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_EPr_R3lJR0E5KLNZf:-N_EVYPWA8AdCu435fdW:bah2568) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/e30ee14e3021a94545a1ee636fbe21295f530bed/src/components/panels/video-panel.vue#L48)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

`(Transcript)` should be lang file'd
</blockquote></details>

Donethanks

**Review by mohsin-r — CHANGES_REQUESTED** [review]
Pretty cool feature and everything works well for the most part. 

Just one bug I found: when you toggle the show transcript on mobile view, everything looks really awkward, as if the transcript covers all the other content, except the map. So you'll see half the transcript, then a random map, and then the rest of the transcript. 

> Reviewed 5 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-:-N_FSJq1AUoR6kYm1X7h:b-lhignf)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[`StoryRampSchema.json` line 279 at r3](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369#-N_FQefQBrdNxYj8H5A4:-N_FQefREW9Iwh4aZVl6:b-goycec) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/8fe9104f1c73dcd7cf0e6fe243b8b34f36609c7f/StoryRampSchema.json#L279)):*
> ```JSON
>                 "src": {
>                     "type": "string",
>                     "description": "The source for the video."
> ```

Would be good to clarify this part e.g. local videos must be a file in the assets folder, external videos must be a URL etc.

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

**Review by spencerwahl — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
