### PR TITLE
add map panels and fix overview map

### LINKED ISSUE #42: Create map panels
Implement the map panel component `map-panel.vue` that creates a RAMP map instance given a simplified RAMP2 config.

### LINKED ISSUE #52: Missing tiles in Overview map
Even after upgrading to RAMP 3.3.4, it appears we still have an issue where overview maps show "tearing" as demonstrated in the screencap below:

image

This issue is to resolve the display glitch in the overview map.

### PR DESCRIPTION
**Pull request by JahidAhmed**
Closes #42 
Closes #52 

Added map panels and the appropriate ID to each map. Also fixes overview map tile issues. Next PR will contain the new schema and updated map configs.

---
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55)

### CODE REVIEW

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @JahidAhmed, @RyanCoulsonCA, and @yileifeng)

___
*[src/components/panels/panel.vue, line 27 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55#-MoifcpM8TH1mqAUOPx8:-MoifcpM8TH1mqAUOPx9:bb73xfv) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/61a0caf620a5d1736d1ea77d958a06364d5a9a53/src/components/panels/panel.vue#L27)):*
> ```Vue
>     @Prop() config!: BasePanel;
>     @Prop() ratio!: boolean;
>     @Prop() id!: number;
> ```

Same
___
*[src/components/story/slide.vue, line 27 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55#-MoifGffC9lCXxDxpW2_:-MoifGffC9lCXxDxpW2a:b-ouscq0) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/61a0caf620a5d1736d1ea77d958a06364d5a9a53/src/components/story/slide.vue#L27)):*
> ```Vue
> export default class SlideV extends Vue {
>     @Prop() config!: Slide;
>     @Prop() id!: number;
> ```

Probably rename this to `idx` since there is also the slide title that is used as id in the story content so name can be confusing

**Review by JahidAhmed — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[src/components/panels/panel.vue, line 27 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55#-MoifcpM8TH1mqAUOPx8:-MoihIjd9BcvynyZLCAd:b-n9tkhd) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/61a0caf620a5d1736d1ea77d958a06364d5a9a53/src/components/panels/panel.vue#L27)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Same
</blockquote></details>

changed
___
*[src/components/story/slide.vue, line 27 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55#-MoifGffC9lCXxDxpW2_:-MoihJOj7qBSA5aQgXYV:bjw8z9l) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/61a0caf620a5d1736d1ea77d958a06364d5a9a53/src/components/story/slide.vue#L27)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Probably rename this to `idx` since there is also the slide title that is used as id in the story content so name can be confusing
</blockquote></details>

changed to `slideIdx` just to differentiate from panel index and any confusion that might cause

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

**Pull request merged**
