### PR TITLE
Add Vue 3 version of Storylines plugin

### PR DESCRIPTION
**Pull request by yileifeng**
Connected to https://github.com/ramp4-pcar4/storylines-editor/pull/242

Adds support for Vue 3 version of the Storylines package that is being used in the editor PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)

### CODE REVIEW

**Review by dnlnashed — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
