### PR TITLE
add customStyles attribute to text panel

### LINKED ISSUE #365: Add `customStyles` attribute to text panel
As discussed on Teams, add a new attribute to the text panel that (if present) will apply custom CSS to the panel.

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #365 

This PR adds a `customStyles` attribute to the text panel configuration. This attribute allows you to apply specific CSS properties to individual panels.

Example Usage, which would add a black border around the text panel:
```json
{
    "title": "Text Panel Title",
    "content": "Text Content",
    "type": "text",
    "customStyles": "border: 2px solid black;"
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/definitions.ts` line 143 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366#-NZX7FHKAnY54W8DQDPi:-NZX7FHKAnY54W8DQDPj:b3qlgs1) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/57f3f4bae0dc08a8ea737a37ec85e09de3a4e016/src/definitions.ts#L143)):*
> ```XML
>     titleTag: string;
>     content: string; // in md format
>     customStyles?: string; // css string
> ```

Minor suggestion. Perhaps we can make this a base panel property and then apply it in `panel.vue`. This would allow customizing all panel types, if a client wanted it in the future or whatever.

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mohsin-r and @yileifeng)

___
*[`src/definitions.ts` line 143 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366#-NZX7FHKAnY54W8DQDPi:-NZXKBVO3T4Qf5_PWkEQ:b-s3gmma) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/57f3f4bae0dc08a8ea737a37ec85e09de3a4e016/src/definitions.ts#L143)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

Minor suggestion. Perhaps we can make this a base panel property and then apply it in `panel.vue`. This would allow customizing all panel types, if a client wanted it in the future or whatever. 
</blockquote></details>

Yep I agree, doesn't hurt to add extra flexibility.

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)* status: all files reviewed, 1 unresolved discussion (waiting on @mohsin-r)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
