### PR TITLE
Lazy Image Loading

### PR DESCRIPTION
**Pull request by roryhofland**
Related to https://github.com/ramp4-pcar4/storylines-editor/pull/194

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Pull request merged**
