### PR TITLE
Scroll to dynamic content on change

### LINKED ISSUE #349: Long text/markdown contents in right panel is opening at the center of contents instead of top
The dashboard in full desktop resolution is quite long, and is opening up in the "middle" of the content. See the screenshots below. The first screenshot is what immediately appears on the right when clicking the highlighted link. The second screenshot is scrolling up to the top of the dashboard content, which is also the top of the left panel content. 

(Example, requires VPN, and this link won't last forever: https://environmental-maps.dev.ec.gc.ca/cws_ramp-storylines_sandbox/index-ca-en.html#/en/priority-species_especes-prioritaires#5-barren-ground-caribou, Barren-ground Caribou slide, "Please refer to our barren-ground caribou dashboard" link)

image

image

### PR DESCRIPTION
**Pull request by spencerwahl**
Closes #349

When dynamic content changes the window will scroll to the top of the right side dynamic panel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
There seems to be a bug when clicking back on the dynamic panel when opening a different text panel. To reproduce, click `longer text section with table` then hit back. The title will change but the MD body content remains unchanged. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351#-:-NVoxyA2BK7mKvGbVCsa:b-8akhvd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Comment by spencerwahl** [comment]
Looks like the bug existed before but good catch, I'll see if I can find a quick fix.

**Review by spencerwahl — COMMENTED** [review]
the fix was very quick

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351#-:-NVp4xpd423sVmvg7l6x:b6f4zbt)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Pull request merged**
