### PR TITLE
add intro slide

### LINKED ISSUE #49: Create introduction slide
Create the large introductory slide component, which contains a logo, title, and subtitle.

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #49 

This PR adds the introduction slide. For now the logo only supports images, but maybe in the future we'd want to support vectors as well.

---
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

**Review by JahidAhmed — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[src/app.vue, line 14 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57#-MonXrIF1KDKmtIoWgil:-MonXrIF1KDKmtIoWgim:b-cxv9eh) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/851a59dbe1dbaa516b66c5133e286a90376e2163/src/app.vue#L14)):*
> ```Vue
>         </header>
> 
>         <introduction :config="config.introSlide"></introduction>
> ```

I think the `id="intro"` got removed that links top hexagon back to top of page

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @JahidAhmed and @yileifeng)

___
*[src/app.vue, line 14 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57#-MonXrIF1KDKmtIoWgil:-MonZ2yY2xkv_d2ST8Yv:b-886gsx) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/851a59dbe1dbaa516b66c5133e286a90376e2163/src/app.vue#L14)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

I think the `id="intro"` got removed that links top hexagon back to top of page
</blockquote></details>

Fixed

**Review by yileifeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @JahidAhmed and @yileifeng)

**Review by JahidAhmed — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
