### PR TITLE
Fix dynamic text content for mobile resolutions

### LINKED ISSUE #331: Mobile layout problems with Text slides
When using a Dynamic slide that links to a right-hand panel type as "text", the content can overlap with existing content and is displayed below the user's field of view.
image
image

Here is some example Markdown that is triggering the problem (you may need to remove linebreaks):
<pre>
Achievements and Future Milestones
----------------------------------

||Achievements|Ongoing Efforts and Planned Milestones|
|-|-|-|
|**Recovery**|*Dolphin and Union population*<p><ul><li>Initiated [Transport Canada's Pro-active Vessel Management program](https://tc.canada.ca/en/marine-transportation/navigation-marine-conditions/proactive-vessel-management) to mitigate shipping/ icebreaking impacts on sea ice crossings</li></ul></p>*Barren-ground population*<p><ul><li>On-the-ground actions for Northwest Territories, Nunavut and Yukon herds through management boards and Indigenous/territorial governments</li><li>On-the-ground partner-led projects, including Indigenous Protected and Conserved Areas initiatives relevant to barren-ground caribou</li></ul></p>|*Dolphin and Union population*<p><ul><li>Continue conservation planning to complete herd-specific plans</li><li>Continue engagement with Indigenous peoples on the Pan-Canadian Approach</li></ul></p>*Barren-ground population*<p><ul><li>Protection of freshwater crossings, access corridors, and calving/post-calving grounds in Nunavut</li><li>Continue conservation planning to complete herd-specific plans</li><li>Continue engagement with Indigenous peoples on the Pan-Canadian Approach</li></ul></p>|
|**Knowledge**|*Dolphin and Union population*<p><ul><li>Identification of knowledge gaps in the national Management Plan and respectful inclusion of Indigenous knowledge in addressing these gaps through negotiated contribution agreementsBarren-ground population</li></ul></p><p><ul><li>Identification of knowledge gaps in herd management plans and respectful inclusion of Indigenous knowledge in addressing these gaps through negotiated contribution agreements</li></ul></p>|*Dolphin and Union population*<p><ul><li>Continue collaborative monitoring programs</li><li>Build on recovery actions identified in the national Management Plan to address additional knowledge gaps and priorities with key partners</li><li>Participate in the North American Caribou Workshop to facilitate knowledge sharing</li></ul></p>*Barren-ground population*<p><ul><li>Continue collaborative monitoring programs</li><li>Address and identify additional knowledge gaps and priorities with key partners</li><li>Participate in the North American Caribou Workshop to facilitate knowledge sharing</li></ul></p>|
|**Reporting**|*Dolphin and Union population*<p><ul><li>Federal and territorial reporting on recovery implementation, including through various agreements’ annual reporting mechanisms and priority species dedicated web pages to communicate progress to Canadians</li></ul></p>*Barren-ground population*<p><ul><li>Federal, provincial, and territorial reporting on recovery implementation, including through various agreements’ annual reporting mechanisms and priority species dedicated web pages to communicate progress to Canadians</li><ul></p>|<ul><li>Ongoing reporting through existing mechanisms and priority species dedicated web pages</li></ul>|
</pre>

This issue is to ensure mobile layout behaves as expected when opening a text panel from a dynamic slide - Opaque background and consistent flow to let the user know this is the content they selected vs. the panel they were just on? Open to ideas.

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #331 

Fixes text content having a fixed height on mobile resolutions resulting in overlapping slides. Added test cases with chart slideshows and long-form text section with table to the dynamic slide for testing purposes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/332)

### CODE REVIEW

**Review by spencerwahl — COMMENTED** [review]
It looks like the table is pushing the content out to the right on mobile (horizontal scrollbar on the site), will presumably be fixed by whatever we use to handle tables this large.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/332#-:-NUc9_I32LMps1CWu5CG:bymfttj)* status: 0 of 2 files reviewed, all discussions resolved

**Review by yileifeng — COMMENTED** [review]
Added a container div to MD rendered <table> elements and horizontal scrolling for tables on mobile. Didn't find a way to make it work with `markdown-it-container` so ended up using regex matching. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/332#-:-NV0ppHJAMKBP-qgA6iK:b-ivorkj)* status: 0 of 3 files reviewed, all discussions resolved

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
