### PR TITLE
handle parsing of csv chart input into configured highcharts options

### LINKED ISSUE #86: Parse local CSV data when initializing chart panel
From #65, find a way to parse local CSV files as chart input. If the CSV file is hosted on a server, it can be passed inside the `csvUrl` parameter as part of the highcharts object constructor and this worked fine. Currently am using the `papa-parse` library for Vue to try to accomplish this.

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #86 

Added the `papa-parse` library to help with parsing CSV DQV chart input. Then turned this into a configured highcharts object to be passed into the constructor and create the chart panel. Some of the configurable options are hardcoded currently but this will be solved in #85. All 3 sample chart files are of the same format currently, so will work with the current logic (but may need to be slightly tweaked if CSV formatting changes with future data). The old `json` input is still there, so in case a user wants to pass in a configured `highcharts` json object themselves that is a viable option too.

Sample output: 
image

---
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[src/components/panels/chart-panel.vue, line 40 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89#-MsjwdBX7-14fGUC4cCY:-MsjwdBX7-14fGUC4cCZ:bld3tcx) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/71da22a6a4c697e94dbc192784f33f97e87295fb/src/components/panels/chart-panel.vue#L40)):*
> ```Vue
>                 // parse JSON data
>                 data.json().then((res) => {
>                     console.log('JSON file input: ', data);
> ```

should console logs be sticking around?

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @spencerwahl)

___
*[src/components/panels/chart-panel.vue, line 40 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89#-MsjwdBX7-14fGUC4cCY:-Msjyej0DDKfqw6LsOvX:b-hfpv0l) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/71da22a6a4c697e94dbc192784f33f97e87295fb/src/components/panels/chart-panel.vue#L40)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

should console logs be sticking around?
</blockquote></details>

removed

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
