### PR TITLE
Issue/pr templates

### PR DESCRIPTION
**Pull request by szczz**
#400 

These are the issue/pr templates used by the RAMP project. Feel free to suggest any changes for Storylines.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/406)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Pull request merged**
