### PR TITLE
Port missing editor viewer code to repo

### PR DESCRIPTION
**Pull request by yileifeng**
Setup work for #347

**Changes**: 
- moved all missing viewer code from editor repo (mostly involving ZIP folder calls for previewing)
- fixes all TS warnings in this repo

**Testing**: 
All functionality should behave normally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/358)

### CODE REVIEW

**Comment by yileifeng** [comment]
[Demo](https://ramp4-pcar4.github.io/story-ramp/port-editor-code/#/en/00000000-0000-0000-0000-000000000000)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by roryhofland — APPROVED** [review]
> Reviewed 21 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
