### PR TITLE
Add top hexagon to navigate to top of page

### LINKED ISSUE #4: Provide a link to the top of the page (left side paginator)
The user can click the top hexagon in the paginator, and will be taken to the very top of the webpage.

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #4

Add option to scroll to top of page

---
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

**Review by JahidAhmed — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[schema.json, line 518 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56#-MoitbcDCK-47F6_YuRf:-MoitbcE0xKyT8iA6dzE:bw52d39) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/8cab5e95ccce3c4c5fb49aa3c0c56973b49d66ad/schema.json#L518)):*
> ```JSON
> 
>     "properties": {
>         "title": {
> ```

this file will need a rebase now due to the file name change

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @JahidAhmed and @RyanCoulsonCA)

___
*[schema.json, line 518 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56#-MoitbcDCK-47F6_YuRf:-Moj5TJ30TDDq_u78vsg:b-896fix) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/8cab5e95ccce3c4c5fb49aa3c0c56973b49d66ad/schema.json#L518)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

this file will need a rebase now due to the file name change
</blockquote></details>

Done.

**Review by JahidAhmed — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
