### PR TITLE
Add support for uploaded video asset files in preview

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
https://github.com/ramp4-pcar4/storylines-editor/issues/408, https://github.com/ramp4-pcar4/storylines-editor/issues/267

### Changes
- [FEATURE] support for handling captions + transcript files transferred from `configFileStructure`
- [FIX] handle locally uploaded video files by appending `src` directly onto video element

### Notes
Published `v3.2.7` to NPM https://www.npmjs.com/package/ramp-storylines_demo-scenarios-pcar

### Testing
Can test in Storylines Editor when package is updated, for now ensure video panels have no errors in demo.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493)

### CODE REVIEW

**Review by szczz — CHANGES_REQUESTED** [review]
I think we should impose a file size limit on this change. Someone could disrespectfully upload a 10 hr rick roll loop, or an 8k video and cause a whole buncha slowness and chaos in the backend. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493#-:-OASyHLNE9YybZ7U_R3a:bpp52a0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
Nvm, this is just extracting the file. Opening an issue in the editor repo to impose a limit.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493#-:-OAT-dE711RdTGcxZSf6:b-t9tarp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
