### PR TITLE
Exclude ramp-pcar from being bundled in NPM plugin build

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
https://github.com/ramp4-pcar4/storylines-editor/issues/380

### Changes
- [BUILD] excluded `ramp-pcar` from being bundled when building project as plugin for NPM
- published new version `3.2.2` to NPM
- updated `ramp-pcar` to `4.8.0`

### Testing
None, needs testing after upgrading version in editor

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/457)

### CODE REVIEW

**Comment by james-rae** [comment]
Did these concerns get proven to be not a problem? https://github.com/ramp4-pcar4/storylines-editor/issues/380#issuecomment-2315742341

Cuz if not this is likely a breaking change for anything consuming `ramp-storylines_demo-scenarios-pcar` from `npm` unless they pinned. 

Is this PR to experiment with what happens? Or has trigger been pulled on this new build strategy?

**Review by yileifeng — COMMENTED** [review]
Yeah created PR mainly to make sure build is still good, but the ramp4-pcar4/storylines-editor#380 (comment) should be no issue here since I did not make any modifications to the `package.json` so nothing changed with this Storylines build as a stand-alone project. Just need to test if editor will work with the new NPM version alongside an updated config editor version. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/457#-:-O5TfKSz4NwUtZMlT_0R:bbj5v0z)* status: 0 of 3 files reviewed, all discussions resolved

**Review by mohsin-r — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/457#-:-O5UdBTB-dY9rv_0uJRy:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
