### PR TITLE
Migrate Storylines to RAMP4 (continued)

### PR DESCRIPTION
**Pull request by yileifeng**
Working off of #377 (testing demo IPR)

~~**No Pulling.**~~
**Ready for full review now.**
Worked on jointly with @roryhofland.

This PR is essentially an enormous rebase of our previous RAMP4 demo in January, with a couple of small enhancements thrown in.
Full list of changes:

* Storylines now uses RAMP4 for map panels
* gutted any RAMP2 styling that was causing conflicts
* config files have been converted to RAMP4
* the Timeslider fixture was ported to RAMP4

There are still a few quirks, some of which may require changes in RAMP4.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)

### CODE REVIEW

**Review by james-rae — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)* status: 2 of 162 files reviewed, all discussions resolved

**Review by spencerwahl — CHANGES_REQUESTED** [review]
Time slider looks like it needs a few CSS tweaks but I can handle that in a new PR after this is merged. Seems to function properly though :heavy_check_mark: 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392#-:-NifOVJi9HINxwiOfjwq:b-olifa2)* status: 2 of 162 files reviewed, 1 unresolved discussion (waiting on @james-rae and @yileifeng)

___
*[`public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json` line 575 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392#-NifOE0O5tIndJFJxyRX:-NifOE0O5tIndJFJxyRY:b-gpazcj) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/aebd1c97f0e6104b6603787281efc48af3e18872/public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json#L575)):*
> ```JSON
>                     "charts": [
>                         {
>                             "src": "ea24000c-7dc3-49a9-baac-c55d28dcaeb9/charts/en/Ethlyene.glycol.release.trends.by.sector.2010-2019.tonnes.csv",
> ```

This slide isn't loading a chart for me, I assume its just pointing to a non-existent csv?

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)* status: 2 of 162 files reviewed, 1 unresolved discussion (waiting on @james-rae and @spencerwahl)

___
*[`public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json` line 575 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392#-NifOE0O5tIndJFJxyRX:-NifU_6V2UPGxjBJL2_c:be5e055) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/aebd1c97f0e6104b6603787281efc48af3e18872/public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json#L575)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

This slide isn't loading a chart for me, I assume its just pointing to a non-existent csv?
</blockquote></details>

Cleaned up the test config

**Review by spencerwahl — APPROVED** [review]
> Reviewed 159 of 162 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 159 of 162 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 159 of 162 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
