### PR TITLE
Migrate Storylines to RAMP4

### PR DESCRIPTION
**Pull request by mohsin-r**
~~**No Pulling.**~~
**Ready for full review now.**
Worked on jointly with @roryhofland.

This PR is essentially an enormous rebase of our previous RAMP4 demo in January, with a couple of small enhancements thrown in.
Full list of changes:

* Storylines now uses RAMP4 for map panels
* gutted any RAMP2 styling that was causing conflicts
* config files have been converted to RAMP4
* the Timeslider fixture was ported to RAMP4

There are still a few quirks, some of which may require changes in RAMP4.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377)

### CODE REVIEW

**Comment by james-rae** [comment]
Map appears really fast. I guess having the story "title / landing" first gives it a few seconds to pull down the library, but from a consumer perspective I would not complain about a lagging load time.

**Comment by mohsin-r** [comment]
Rebased.

**Review by yileifeng — COMMENTED** [review]
Looks like a bunch of styling issues present on the demo page. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377#-:-Nie5eAM5WwLB8xb3gv-:b6a9rlh)* status: 0 of 165 files reviewed, all discussions resolved

**Comment by spencerwahl** [comment]
It seems like at least some of the issues are causes by a github pages 404 styling block? Hard to tell for sure.

**Review by dnlnashed — COMMENTED** [review]
Worth mentioning that if you render all possible R4 instances in the demo (including the Map Panel option in the "This Slide Is Dynamic" section), you'll have 9 instances running, which is 18 webgl contexts (2 per instance, 16 being the limit) used and you can see the console warning 
`Too many active WebGL contexts. Oldest context will be lost`
making all instances :boom: 

A potential fix that is doing a `null` check in RAMP for when the map reacts to an extent change as Mohsin mentioned [here](https://github.com/ramp4-pcar4/ramp4-pcar4/issues/1908), and changing some code in Storylines so that when the instance is visible render it (already done here), but when its not visible on the screen remove it.

Still working on some other solutions that avoids changing Storylines code with ESRI's `tryFatalErrorRecovery`, but I've tried this with the marketing site and it looks like it works, can try it with storylines once this PR is merged.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377#-:-NieILJn88JZxxY4rJLj:bu9wu1v)* status: 0 of 165 files reviewed, all discussions resolved

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 149 of 162 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377)* status: 164 of 165 files reviewed, 2 unresolved discussions (waiting on @mohsin-r)

___
*[`public/scripts/update.js` line 11 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377#-NieMXMiCrqG2KQvKDyz:-NieMXMiCrqG2KQvKDz-:bmobhyz) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/589df49afb295c95fa0c50e3ac9f791f6c6bde4d/public/scripts/update.js#L11)):*
> ```JavaScript
> const [, , base] = argv;
> 
> const fileNames = ['ramp.css', 'ramp.js', 'ramp.esm.js'];
> ```

is there a reason for copying the `esm` version of the library? I don't see it currently in this PR. Unless it's needed, this is just adding another 10mb to the repo every time it runs.
___
*[`src/components/panels/helpers/time-slider/time-slider.vue` line 134 at r2](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/377#-NieNZA2BgxNIdrvNWSH:-NieNZA2BgxNIdrvNWSI:b-gvhjuw) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/589df49afb295c95fa0c50e3ac9f791f6c6bde4d/src/components/panels/helpers/time-slider/time-slider.vue#L134)):*
> ```Vue
>             props.rInstance.geo.layer
>                 .allLayers()
>                 .filter((l: any) => l.supportsFeatures)
> ```

maybe might need to also filter out any layer with `cosmetic` being true? Would need to test but this might do funny stuff to highlighting or any general overlays.

**Comment by spencerwahl** [comment]
#392 continued this PR and was merged, closing this one

**Pull request closed without merging**
