### PR TITLE
Remove editor content from codebase for Storylines release

### PR DESCRIPTION
**Pull request by yileifeng**
Related to #298 

Removes all editor-related code to prepare for 1.0 Storylines release. No merge until separate editor repo/branch cloned.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/310)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 110 of 110 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
Block until editor is separated

**Review by spencerwahl — APPROVED** [review]
> Reviewed 110 of 110 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
Its already separated, merging

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/310#-:-NKy_lT51mUro7Wzp-cX:b-2ko2qj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
