### PR TITLE
improve background image loading

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Changes
- Background images are converted to a BLOB after first load and is cached. Should hopefully make background image loading faster.
- I've also increased animation times by 0.1 to hopefully look a tad bit smoother.

### Testing
Steps:
1. I've temporarily included the TCEI-IECT product in this PR. You can access it by changing the `00000000-0000-0000-0000-000000000000` to `TCEI-IECT` in the demo URL.
2. Ensure images are transitioning smoothly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)

### CODE REVIEW

**Review by spencerwahl — APPROVED** [review]
> Reviewed 99 of 99 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by szczz — APPROVED** [review]
> Reviewed 99 of 99 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

**Review by yileifeng — COMMENTED** [review]
> Reviewed 1 of 99 files at r1, 98 of 98 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
