### PR TITLE
add support for transitional background images

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
#401 

### Changes
- Adds support for transitional background images. The configuration flag is `backgroundImage` and takes a path to an image. 
- When a background is active, text components (text slides, captions, titles, etc.) will be placed in a semi-transparent container to keep an accessible contrast.

### Testing
Steps:
1. Open the sample page and scroll down.
2. Ensure that contrast is OK for text, captions, titles, etc.
3. Ensure that everything is working well on mobile.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417)

### CODE REVIEW

**Review by KashishMistry — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by szczz — APPROVED** [review]
Looks great, I might have missed it, but is the text colour in the text components configurable? The lack of contrast between black text and darker images likely violates some accessibility rules / UI standards. 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417#-:-NujiaXo1f_Spr8xyLKs:bcw8glo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
I set the opacity of the background such that the contrast should be fine (and the few I tested did pass), but either way I think adding an option to configure the colour would be a good idea. I'll add that in!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417#-:-NujnhD_4S_RtNZYh8Jq:bgcni1u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
I've added a config option to `dynamic` and `text` panels to customize the colour of the text. There's a minor issue with bolded text still showing in black (as a result of the `prose` class), but we can make a new issue for this. I've also updated the schema to reflect the config changes made in this PR.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417#-:-Nv3EOaK1fu9sAwVEFCS:beeddhv)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @KashishMistry, @szczz, and @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
