### PR TITLE
Add documentation for plugin usage in NPM

### LINKED ISSUE #368: Update README.md for plugin usage
Update documentation for how to import and use `ramp-storylines` package inside a different Vue project. Re-publish to NPM after complete. Not quite fully tested for integration into other projects (marketing site, storylines editor) so could be more info to be added.

Use this template for reference: 

**Usage**: 
1. Install the ramp-storylines package from npm:
```
npm install ramp-storylines
```

2. Install the plugin in your Vue app:
```
import StorylinesViewer from 'ramp-storylines'
Vue.use(StorylinesViewer);
```

3. Import `i18n` instance from the plugin :
```
import { storylinesI18n } from 'ramp-storylines';
...either inject it in Vue instance or merge messages with existing i18n instance
```

4. Use the components in your Vue templates, here is a demo usage: 
```
<!-- Display the intro slide -->
<story-intro :config="config.introSlide" />

<!-- Display the story content -->
<div class="w-full mx-auto pb-10" id="story">
      <story-content :config="config" />
</div>
```

5. Provide config/schema/demo information

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #368 

Provided documentation for usage as Vue plugin. Not yet published to NPM, but once everything is functional and approved for Marketing site and editor repos we can create a proper 1.0.0 release with these docs included.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)

### CODE REVIEW

**Comment by yileifeng** [comment]
TODO: upgrade to Vue 3 usage

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Updated doc for Vue 3 use

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380#-:-NrfS1BCCQZL241Jztvc:b-apd16x)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
